# Generated by Django 3.1.3 on 2020-11-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konstruktor', '0002_auto_20201128_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='external_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
