# Generated by Django 3.1.3 on 2020-11-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konstruktor', '0003_vacancy_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='compensation_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='compensation_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
