# Generated by Django 3.1.3 on 2020-11-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konstruktor', '0004_auto_20201128_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirements',
            field=models.ManyToManyField(to='konstruktor.Requirement'),
        ),
    ]
