# Generated by Django 3.1.3 on 2020-11-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konstruktor', '0005_auto_20201128_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='title',
            field=models.CharField(max_length=955),
        ),
    ]
