# Generated by Django 3.1.3 on 2020-11-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konstruktor', '0009_auto_20201128_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name': 'условия работы',
                'verbose_name_plural': 'условия работы',
            },
        ),
        migrations.AlterModelOptions(
            name='requirement',
            options={'verbose_name': 'Требования', 'verbose_name_plural': 'Требования'},
        ),
        migrations.AlterModelOptions(
            name='responsibility',
            options={'verbose_name': 'Обязаности', 'verbose_name_plural': 'Обязаности'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Навыки', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'ввакансия', 'verbose_name_plural': 'вакансии'},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='conditions',
            field=models.ManyToManyField(to='konstruktor.Condition'),
        ),
    ]
