# Generated by Django 3.1.3 on 2020-11-28 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('konstruktor', '0010_auto_20201128_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=75, null=True)),
            ],
            options={
                'verbose_name': 'условия работы',
                'verbose_name_plural': 'условия работы',
            },
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Employment',
                'verbose_name_plural': 'Employment',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'WorkExperience',
                'verbose_name_plural': 'WorkExperience',
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'WorkSchedule',
                'verbose_name_plural': 'WorkSchedule',
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='konstruktor.area'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='konstruktor.employment'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='konstruktor.workexperience'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='konstruktor.workschedule'),
        ),
    ]
