# Generated by Django 3.1.3 on 2020-11-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konstruktor', '0012_auto_20201128_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employment',
            options={'verbose_name': 'занятость', 'verbose_name_plural': 'занятость'},
        ),
        migrations.AlterModelOptions(
            name='workschedule',
            options={'verbose_name': 'график работы', 'verbose_name_plural': 'график работы'},
        ),
    ]
